# Use the official PostgreSQL image from the Docker Hub
FROM postgres:latest

# Set environment variables for PostgreSQL
# ENV POSTGRES_USER=your_username
# ENV POSTGRES_PASSWORD=your_password
# ENV POSTGRES_DB=your_database

# Copy any custom scripts or configuration files
# COPY ./init.sql /docker-entrypoint-initdb.d/

# Expose the PostgreSQL port
EXPOSE 5432
