version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: demo_posgres
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: darpan
      POSTGRES_PASSWORD: Admin@12345
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - demo_posgres:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  demo_posgres:


networks:
  my_network:
